### ISSUE TITLE
Create custom user admin page

### ISSUE THREAD

**Issue by KaitoMizukami** [KaitoMizukami/skba#3]
# Task
Create a custom user admin page to be able to create and modify user account
- [x]  Create forms.py for user creation and edit.
- [x] Create custom user admin page to manage user account
- [x]  Register it in admin.py
